/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estructuras.UbicacionActual;
import java.awt.geom.Point2D;
import java.io.*;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;
import maps.java.Geocoding;
import maps.java.MapsJava;
import Estructuras.Grafo;

/**
 *
 * @author Rolo
 */
public class GestionLugarDestino extends javax.swing.JFrame {
    
    DefaultListModel<String> listModel;
    int contador = 0;
    private UbicacionActual ubicacion = new UbicacionActual();
    /**
     * Creates new form GestionLugarDestino
     */
    public GestionLugarDestino() {
        initComponents();
        MapsJava.setKey("AIzaSyBXTa2acjXrIwo0QQLj5bKl48h08qIMpNs");
        listModel = new DefaultListModel<>();
    }
    
    private void buscarDireccion () throws UnsupportedEncodingException, MalformedURLException{
        if(!DireccionGestTxtField.getText().isEmpty()){
            Geocoding datosUbi = new Geocoding();
            Point2D.Double resultadoDir = datosUbi.getCoordinates(DireccionGestTxtField.getText());
            if(resultadoDir.x != 0.0 && resultadoDir.y != 0.0){
                DireccionEncGest.setText(datosUbi.getAddressFound());
                
                ubicacion.setDireccion(datosUbi.getAddressFound());
                ubicacion.setLatitud(resultadoDir.x);
                ubicacion.setLongitud(resultadoDir.y);
            }else{
                JOptionPane.showMessageDialog(null, "No se encuentra el lugar");
            }
        
        }else{
            JOptionPane.showMessageDialog(null, "Llene el espacio");
        }
    }
    
    private void buscarCoordenadas () throws UnsupportedEncodingException, MalformedURLException{
        if(!LtdTxtField.getText().isEmpty() && !LngTxtField.getText().isEmpty()){
            Geocoding coor = new Geocoding();
            double latitud = Double.parseDouble(LtdTxtField.getText());
            double longitud = Double.parseDouble(LngTxtField.getText());
            ArrayList<String> resultadoCoo = coor.getAddress(latitud, longitud);
            String resultado = resultadoCoo.get(0);
            
            DireccionEncGest.setText(resultado);
        }else{
            JOptionPane.showMessageDialog(null, "Llene el espacio");
        }
    }
//    public void eliminarLugar() throws FileNotFoundException, IOException{
//        int index = LugaresAgregadosJlist.getSelectedIndex();
//        listModel.remove(index);
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DireccionGestTxtField = new javax.swing.JTextField();
        BuscarDirGesBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        LtdTxtField = new javax.swing.JTextField();
        LngTxtField = new javax.swing.JTextField();
        BuscarCooGestBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DireccionEncGest = new javax.swing.JTextField();
        AgregarDestinoBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LugaresAgregadosJlist = new javax.swing.JList<>();
        EliminarLugarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Gestión de Lugares");

        jLabel2.setText("Dirección:");

        BuscarDirGesBtn.setText("Buscar por Dirección");
        BuscarDirGesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarDirGesBtnMouseClicked(evt);
            }
        });

        jLabel3.setText("Latitud:");

        jLabel4.setText("Longitud:");

        BuscarCooGestBtn.setText("Buscar por Coordenadas");
        BuscarCooGestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarCooGestBtnMouseClicked(evt);
            }
        });

        jLabel5.setText("Dirección:");

        DireccionEncGest.setEditable(false);

        AgregarDestinoBtn.setText("Agregar destino");
        AgregarDestinoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarDestinoBtnMouseClicked(evt);
            }
        });

        jLabel6.setText("Fecha:");

        jScrollPane1.setViewportView(LugaresAgregadosJlist);

        EliminarLugarBtn.setText("Eliminar Lugar");
        EliminarLugarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarLugarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(DireccionGestTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BuscarDirGesBtn))
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(LtdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LngTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(45, 45, 45)
                            .addComponent(BuscarCooGestBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DireccionEncGest))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AgregarDestinoBtn))
                        .addComponent(jScrollPane1))
                    .addComponent(EliminarLugarBtn))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(DireccionGestTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarDirGesBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LtdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(LngTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BuscarCooGestBtn)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DireccionEncGest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(AgregarDestinoBtn))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarLugarBtn)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarDirGesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarDirGesBtnMouseClicked
        try {
            this.buscarDireccion();
        } catch (Exception ex) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDirGesBtnMouseClicked

    private void BuscarCooGestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarCooGestBtnMouseClicked
        try {
            this.buscarCoordenadas();
        } catch (Exception ex) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCooGestBtnMouseClicked

    private void AgregarDestinoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarDestinoBtnMouseClicked
        String lugar = DireccionEncGest.getText().toString();
        if(lugar.equals("")){
            JOptionPane.showMessageDialog(null, "No hay información encontrada");
        }else{
        try {
            contador=contador+1;
            Grafo grafo = new Grafo();
            grafo.agregarVertice(contador);
            listModel.addElement(contador+" " + lugar);
            LugaresAgregadosJlist.setModel(listModel);
            
            FileWriter writer = new FileWriter("Lugares.txt", true);
            writer.write(contador+" " + lugar);
            writer.write(System.getProperty("line.separator"));
            writer.close();
            JOptionPane.showMessageDialog(null, "Agregado");
            DireccionEncGest.setText("");
            grafo.imprimeGrafo();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        }
    }//GEN-LAST:event_AgregarDestinoBtnMouseClicked

    private void EliminarLugarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLugarBtnMouseClicked
        int index = LugaresAgregadosJlist.getSelectedIndex();
        String s = LugaresAgregadosJlist.getSelectedValue();
        String word = s.substring(0, 1);
        int foo = Integer.parseInt(word);
        listModel.remove(index);
        Grafo grafo = new Grafo ();
        grafo.eliminarVertice(foo);
        
        try{
            FileReader fr = new FileReader("Lugares.txt");
            BufferedReader br = new BufferedReader(fr);
            
            String line = br.readLine();
            
            while ((line = br.readLine()) != null && line.indexOf(s) == -1){
                System.out.println(line);
                FileWriter writer = new FileWriter("Lugares.txt", true);
                writer.write("");
                writer.close();
            }
            br.close();
        }catch (IOException e){
            System.out.println("File not found");
        }
        
        
   
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarLugarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLugarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLugarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLugarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLugarDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionLugarDestino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDestinoBtn;
    private javax.swing.JButton BuscarCooGestBtn;
    private javax.swing.JButton BuscarDirGesBtn;
    private javax.swing.JTextField DireccionEncGest;
    private javax.swing.JTextField DireccionGestTxtField;
    private javax.swing.JButton EliminarLugarBtn;
    private javax.swing.JTextField LngTxtField;
    private javax.swing.JTextField LtdTxtField;
    private javax.swing.JList<String> LugaresAgregadosJlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
