/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;


import Estructuras.Arbol;
import Estructuras.BinarySearchTree;
import Estructuras.Grafo;
import Estructuras.TreeNode;
import java.util.*;
import Estructuras.UbicacionActual;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.geom.Point2D;
import java.io.FileWriter;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import javax.swing.JOptionPane;
import maps.java.Geocoding;
import maps.java.MapsJava;
/**
 *
 * @author Rolo
 */
public class Inicio extends javax.swing.JFrame {
    int contador = 0;
    private UbicacionActual ubicacion = new UbicacionActual();
    private Arbol arbol = new Arbol();
    /**
     * Creates new form GestionLugaresDestino
     */
    public Inicio() {
        initComponents();
        MapsJava.setKey("AIzaSyBXTa2acjXrIwo0QQLj5bKl48h08qIMpNs");
    }
    
    private void buscarDireccion () throws UnsupportedEncodingException, MalformedURLException{
        if(!DireccionTxtField.getText().isEmpty()){
            Geocoding datosUbi = new Geocoding();
            Point2D.Double resultadoDir = datosUbi.getCoordinates(DireccionTxtField.getText());
            if(resultadoDir.x != 0.0 && resultadoDir.y != 0.0){
                DireccionEncontrada.setText(datosUbi.getAddressFound());
                
                ubicacion.setDireccion(datosUbi.getAddressFound());
                ubicacion.setLatitud(resultadoDir.x);
                ubicacion.setLongitud(resultadoDir.y);
                
                arbol.setNombre(datosUbi.getAddressFound());
            }else{
                JOptionPane.showMessageDialog(null, "No se encuentra el lugar");
            }
        
        }else{
            JOptionPane.showMessageDialog(null, "Llene el espacio");
        }
    }
    
    private void buscarCoordenadas () throws UnsupportedEncodingException, MalformedURLException{
        if(!LatitudTxtField.getText().isEmpty() && !LongitudTxtField.getText().isEmpty()){
            Geocoding coor = new Geocoding();
            double latitud = Double.parseDouble(LatitudTxtField.getText());
            double longitud = Double.parseDouble(LongitudTxtField.getText());
            ArrayList<String> resultadoCoo = coor.getAddress(latitud, longitud);
            String resultado = resultadoCoo.get(0);
            
            DireccionEncontrada.setText(resultado);
        }else{
            JOptionPane.showMessageDialog(null, "Llene el espacio");
        }
    }
    
    private Boolean comprobarDireccion(){
        if(ubicacion.getLatitud() != 0.0 && ubicacion.getLongitud() != 0.0 && ubicacion.getDireccion() != null){
            return true;
        }else{
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DireccionTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LatitudTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LongitudTxtField = new javax.swing.JTextField();
        BuscarDirBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BuscarCooBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DireccionEncontrada = new javax.swing.JTextField();
        ContinuarBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DireccionTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionTxtFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("¿En dónde se encuentra usted?");

        jLabel2.setText("Dirección:");

        jLabel3.setText("Latitud:");

        jLabel4.setText("Longitud:");

        BuscarDirBtn.setText("Buscar por dirección");
        BuscarDirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarDirBtnMouseClicked(evt);
            }
        });

        BuscarCooBtn.setText("Buscar por coordenadas");
        BuscarCooBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarCooBtnMouseClicked(evt);
            }
        });

        jLabel5.setText("Dirección:");

        DireccionEncontrada.setEditable(false);

        ContinuarBtn.setText("Continuar");
        ContinuarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContinuarBtnMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setText("Escriba su modo de transporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DireccionEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DireccionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(BuscarDirBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LongitudTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LatitudTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(52, 52, 52)
                                        .addComponent(BuscarCooBtn))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContinuarBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DireccionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(BuscarDirBtn))
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(LatitudTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(LongitudTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(BuscarCooBtn))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DireccionEncontrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(ContinuarBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DireccionTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionTxtFieldActionPerformed

    private void BuscarDirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarDirBtnMouseClicked
        try {
            this.buscarDireccion();
        } catch (Exception ex) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarDirBtnMouseClicked

    private void BuscarCooBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarCooBtnMouseClicked
        try {
            this.buscarCoordenadas();
        } catch (Exception ex) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCooBtnMouseClicked

    private void ContinuarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContinuarBtnMouseClicked
        if(this.comprobarDireccion()==true){
            this.setVisible(false);
            GestionLugarDestino lugarDestinoVentana = new GestionLugarDestino();
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            lugarDestinoVentana.setLocation((d.width/2)-(lugarDestinoVentana.getWidth()/2), 
                    (d.height/2)-(lugarDestinoVentana.getHeight()/2));
            lugarDestinoVentana.setSize(new Dimension(400, 350));
            lugarDestinoVentana.setVisible(true);
        }
        try {
            contador=contador+1;
            
            Grafo grafo = new Grafo();
            grafo.agregarVertice(contador);
            
//            BinarySearchTree arbol = new BinarySearchTree();
//            arbol.insert(DireccionEncontrada.getText());
            Arbol arbolActual = new Arbol();
            arbolActual.setNombre(DireccionEncontrada.getText());
            
            FileWriter writer = new FileWriter("Lugares.txt", true);
            writer.write(contador+" " + DireccionEncontrada.getText());
            writer.write(System.getProperty("line.separator"));
            writer.close();
            
            FileWriter writer2 = new FileWriter("Favoritos.txt", true);
            writer2.write(DireccionEncontrada.getText());
            writer2.write(System.getProperty("line.separator"));
            writer2.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinuarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarCooBtn;
    private javax.swing.JButton BuscarDirBtn;
    private javax.swing.JButton ContinuarBtn;
    private javax.swing.JTextField DireccionEncontrada;
    private javax.swing.JTextField DireccionTxtField;
    private javax.swing.JTextField LatitudTxtField;
    private javax.swing.JTextField LongitudTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
